### ISSUE TITLE
chapter6/listing09 there are other results

### ISSUE THREAD

**Issue by qshuai** [goinaction/code#21]
Final Counter :  sometime equal 2 and sometime 4

go version : 1.9.0
macbook pro 10.12.6

**Comment by billhathaway** [comment]
The goal of that program is to demonstrate race conditions by showing inconsistent results due to the combination of concurrency and lack of locking.

The comments at the top say
// This sample program demonstrates how to create race
// conditions in our programs. We don't want to do this

I think what you are seeing is expected.

**Comment by ardan-bkennedy** [comment]
@billhathaway I love your description better. I might use it.

@scrapup is excellent you saw the inconsistency of the undefined behavior. It is exactly what I wanted you to see!
